<?xml version="1.0" encoding="utf-8"?>
<Project>
  <ItemGroup>
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.2" />
    <PackageVersion Include="BenchmarkDotNet.Diagnostics.Windows" Version="0.15.2" />
    <PackageVersion Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageVersion Include="BlazorMonaco" Version="3.3.0" />
    <PackageVersion Include="BlazorSplitGrid" Version="1.8.0" />
    <PackageVersion Include="CliWrap" Version="3.9.0" />
    <PackageVersion Include="CodeBeam.MudBlazor.Extensions" Version="6.9.2" />
    <PackageVersion Include="CommandLineParser" Version="2.9.1" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="coverlet.msbuild" Version="6.0.4" />
    <PackageVersion Include="docopt.net" Version="0.8.1" />
    <PackageVersion Include="DotNet.ReproducibleBuilds" Version="1.2.25" />
    <PackageVersion Include="DotNetEnv" Version="3.1.1" />
    <PackageVersion Include="Dunet" Version="1.11.3" />
    <PackageVersion Include="eController.CodeStyle" Version="1.1.18" />
    <PackageVersion Include="eController.WebUI.Library" Version="4.0.13" />
    <!--TODO Remove eHub.PlugIn -->
    <PackageVersion Include="eHub.PlugIn" Version="1.12.2" />
    <!--TODO DELETE eController.Mfc.Library WHEN OTHER REPOS MERGED -->
    <PackageVersion Include="eController.Mfc.Library" Version="3.9.0" />
    <PackageVersion Include="eController.Util" Version="3.1.1" />
    <PackageVersion Include="eController.Util.Embed" Version="3.1.1" />
    <PackageVersion Include="eController.WebUI.PlugIn" Version="2.0.12" />
    <PackageVersion Include="eController.WebUI.Utility" Version="4.0.12" />
    <PackageVersion Include="ElementLogic.Configuration" Version="0.13.19" />
    <PackageVersion Include="ElUI.BlazorDiagrams" Version="1.2.1" />
    <PackageVersion Include="ElUI.BlazorDiagrams.Serialization" Version="1.2.1" />
    <PackageVersion Include="ElUI.ComponentLib" Version="3.3.0" />
    <PackageVersion Include="eMessenger" Version="1.7.20" />
    <PackageVersion Include="ePlugin.Engine" Version="3.0.11" />
    <PackageVersion Include="ePlugin.MsBuild" Version="2.4.17" />
    <PackageVersion Include="eScheduler.Library" Version="1.1.3" />
    <PackageVersion Include="eScheduler.Library.Abstractions" Version="1.0.1" />
    <PackageVersion Include="eScheduler.UI" Version="1.1.2" />
    <PackageVersion Include="FluentAssertions" Version="[7.2.0]" />
    <PackageVersion Include="FluentValidation" Version="11.11.0" />
    <PackageVersion Include="JsonPatch.Net" Version="3.3.0" />
    <PackageVersion Include="JsonPath.Net" Version="2.1.1" />
    <PackageVersion Include="JsonSchema.Net" Version="7.3.4" />
    <PackageVersion Include="JsonSchema.Net.Generation" Version="5.0.3" />
    <PackageVersion Include="JsonSchema.Net.Generation.DataAnnotations" Version="1.2.0" />
    <PackageVersion Include="JunitXml.TestLogger" Version="5.0.0" />
    <PackageVersion Include="LoxSmoke.DocXml" Version="3.8.0" />
    <PackageVersion Include="Meziantou.Extensions.Logging.Xunit.v3" Version="1.1.6" />
    <PackageVersion Include="Microsoft.AspNetCore.Hosting.Server.Abstractions" Version="2.3.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Razor.Language" Version="6.0.36" />
    <PackageVersion Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
    <PackageVersion Include="Microsoft.Build.Locator" Version="1.9.1" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Common" Version="4.14.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="4.14.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.14.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Razor" Version="6.0.36" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="4.14.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="4.14.0" />
    <PackageVersion Include="Microsoft.Css.Parser" Version="1.0.0" />
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="6.0.2" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.6" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.6" />
    <PackageVersion Include="Microsoft.Extensions.Http.Polly" Version="9.0.6" />
    <PackageVersion Include="Microsoft.Extensions.TimeProvider.Testing" Version="9.5.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="Microsoft.NETCore.Platforms" Version="7.0.4" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="17.14.1" />
    <PackageVersion Include="Microsoft.Testing.Extensions.TrxReport" Version="1.6.2" />
    <PackageVersion Include="Microsoft.TestPlatform" Version="17.13.0" />
    <PackageVersion Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.13.2" />
    <PackageVersion Include="MSTest.Analyzers" Version="3.9.3" />
    <PackageVersion Include="MSTest.TestAdapter" Version="3.9.3" />
    <PackageVersion Include="MSTest.TestFramework" Version="3.9.3" />
    <PackageVersion Include="MvsSln" Version="2.7.0" />
    <PackageVersion Include="Nerdbank.GitVersioning" Version="3.7.115" />
    <PackageVersion Include="NLog" Version="5.5.0" />
    <PackageVersion Include="NLog.Database" Version="5.5.0" />
    <PackageVersion Include="NLog.Extensions.Logging" Version="5.5.0" />
    <PackageVersion Include="NLog.Targets.Loki" Version="2.2.0" />
    <PackageVersion Include="NLog.Web.AspNetCore" Version="5.5.0" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageVersion Include="NSubstitute" Version="5.3.0" />
    <PackageVersion Include="NSubstitute.Analyzers.CSharp" Version="1.0.17" />
    <PackageVersion Include="NuGet.Protocol" Version="6.14.0" />
    <PackageVersion Include="NuGet.Versioning" Version="6.14.0" />
    <PackageVersion Include="Octopus.Client" Version="15.2.2178" />
    <PackageVersion Include="Opc.UaFx.Advanced" Version="2.50.1" />
    <PackageVersion Include="Opc.UaFx.Client" Version="2.42.3" />
    <PackageVersion Include="OPCFoundation.NetStandard.Opc.Ua.Client" Version="1.5.374.78" />
    <PackageVersion Include="OpenTelemetry" Version="1.12.0" />
    <PackageVersion Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.11.2-beta.1" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.12.0" />
    <PackageVersion Include="Polly" Version="8.5.2" />
    <PackageVersion Include="PolySharp" Version="1.15.0" />
    <PackageVersion Include="Pose" Version="1.2.1" />
    <PackageVersion Include="RabbitMQ.Client" Version="7.1.2" />
    <PackageVersion Include="RichardSzalay.MockHttp" Version="7.0.0" />
    <PackageVersion Include="Riok.Mapperly" Version="4.2.1" />
    <PackageVersion Include="Spectre.Console.Cli" Version="0.50.0" />
    <PackageVersion Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.11" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="7.3.2" />
    <PackageVersion Include="System.Data.OleDb" Version="9.0.5" />
    <PackageVersion Include="System.Data.SqlClient" Version="4.9.0" />
    <PackageVersion Include="System.Drawing.Common" Version="9.0.5" />
    <PackageVersion Include="System.Net.Http.Json" Version="9.0.5" />
    <PackageVersion Include="Terminal.Gui" Version="1.19.0" />
    <PackageVersion Include="Testably.Abstractions" Version="9.0.0" />
    <PackageVersion Include="Testably.Abstractions.Testing" Version="4.3.2" />
    <PackageVersion Include="TextCopy" Version="6.2.1" />
    <PackageVersion Include="xunit.extensibility.core" Version="2.9.3" />
    <PackageVersion Include="xunit.v3" Version="2.0.3" />
    <PackageVersion Include="xunit.v3.extensibility.core" Version="2.0.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.0" />
    <PackageVersion Include="Yarp.ReverseProxy" Version="2.3.0" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
    <!-- Shared versions for multitargeted projects -->
    <PackageVersion Include="Basic.Reference.Assemblies.Net90" Version="1.8.2" />
    <PackageVersion Include="System.Reflection.MetadataLoadContext" Version="9.0.5" />
    <PackageVersion Include="System.IO.Pipelines" Version="9.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.5" />
    <PackageVersion Include="Microsoft.Extensions.FileSystemGlobbing" Version="9.0.5" />
    <PackageVersion Include="Microsoft.AspNetCore.Components" Version="9.0.5" />
    <!-- Main versions for our app -->
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.6" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Authorization" Version="9.0.5" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Web" Version="9.0.5" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.5" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.5" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.6" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.6" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="9.0.6" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.6" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.6" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.6" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.6" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.CommandLine" Version="9.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="9.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="9.0.5" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="9.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.6" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="9.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="9.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="9.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="9.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="9.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="9.0.5" />
    <PackageVersion Include="Microsoft.JSInterop" Version="9.0.5" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <!-- Shared versions for multitargeted projects -->
    <PackageVersion Include="Basic.Reference.Assemblies.Net80" Version="1.8.2" />
    <PackageVersion Include="System.Reflection.MetadataLoadContext" Version="8.0.1" />
    <PackageVersion Include="System.IO.Pipelines" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="8.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.FileSystemGlobbing" Version="8.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Components" Version="8.0.16" />
  </ItemGroup>
</Project>