<Project>
    <PropertyGroup>
        <Company>Element Logic</Company>

        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <StaticWebAssetFingerprintingEnabled>false</StaticWebAssetFingerprintingEnabled>

        <DefaultMultitarget>net8.0;net9.0</DefaultMultitarget>
        <DefaultLangVersion>13</DefaultLangVersion>
        <!--<GenerateCompatibilitySuppressionFile>true</GenerateCompatibilitySuppressionFile>-->
    </PropertyGroup>

    <PropertyGroup Condition="$(ProjectName.EndsWith('.Tests')) Or $(ProjectName.EndsWith('.Documentation'))">
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>
    <ItemGroup Condition="$(ProjectName.EndsWith('.Tests')) Or $(ProjectName.EndsWith('.Documentation'))">
        <!-- Testing Frameworks -->
        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.msbuild">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="JunitXml.TestLogger"/>

        <!-- Mocking -->
        <PackageReference Include="NSubstitute"/>
        <PackageReference Include="NSubstitute.Analyzers.CSharp">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

        <!-- Testing -->
        <PackageReference Include="xunit.v3"/>
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

        <!-- Testing Helpers  -->
        <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
        <PackageReference Include="Meziantou.Extensions.Logging.Xunit.v3"/>
        <PackageReference Include="FluentAssertions"/>

        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Nerdbank.GitVersioning" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup Condition="$(ProjectName) != 'eController.CodeStyle'">
        <EditorConfigFiles Include="$(SolutionDir)eController.CodeStyle/files/*.globalconfig" />
    </ItemGroup>
</Project>
