<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="eController.Util" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\eHub\eHub.csproj" />
    </ItemGroup>

</Project>
